### ISSUE TITLE
 openfdat //.pivot_root: permission denied

### ISSUE THREAD

**Issue by rabbitLove520** [teddyking/ns-process#1]
Run the program as root, got the error.

**Comment by teddyking** [comment]
Hi @salamander-mh , what version of go are you using and what operating system?

**Comment by rabbitLove520** [comment]
@teddyking  `go 1.13.4`
os: `Ubuntu 18.03`

**Comment by teddyking** [comment]
Ah ok I see - this isn't totally unexpected.
The program is intended to be run as a non-root user, there's some further info about why/how this works in the accompanying article here: https://medium.com/@teddyking/namespaces-in-go-user-a54ef9476f2a.

Hope that helps!
